### ISSUE TITLE
Add project: PyOptInterface

### ISSUE THREAD

**Issue by metab0t** [jinningwang/best-of-ps#108]
**Project details:**

- Project Name: PyOptInterface
- Github URL: https://github.com/metab0t/PyOptInterface
- Category:  opl
- License: MPL-2.0
- Package Managers: pypi

**Additional context:**

PyOptInterface is an efficient modeling interface for mathematical optimization, and it would be awesome if it can be included by this list.

**Comment by jinningwang** [comment]
Thanks for the information!
A PR is there, https://github.com/jinningwang/best-of-ps/pull/109, would you mind doing a code review for it?

**Comment by metab0t** [comment]
Thanks for the PR!

**Comment by jinningwang** [comment]
No problem. It will show up in next week's update.
