### ISSUE TITLE
Add project: cimpyorm

### ISSUE THREAD

**Issue by FGH-Froehlich** [jinningwang/best-of-ps#120]
**Project details:**

- Project Name: cimpyorm
- Github URL: https://github.com/RWTH-IAEW/cimpyorm
- Category:  Interface
- License: BSD 3-Clause License
- Package Managers: Available on pip (https://pypi.org/project/cimpyorm/)

**Additional context:**

Anothe interface, trying to make CGMES Grid data available on Python.

**Comment by jinningwang** [comment]
Thanks for your attention and help! I'll try to work on this recently.

**Comment by jinningwang** [comment]
@FGH-Froehlich this is the PR, https://github.com/jinningwang/best-of-ps/pull/123
Please let me know if it looks good to you

**Comment by FGH-Froehlich** [comment]
Looks good for me! Thank you.
