### ISSUE TITLE
Add project: DSSData

### ISSUE THREAD

**Issue by felipemarkson** [jinningwang/best-of-ps#55]
**Project details:**

- Project Name: DSSData
- Github URL:https://github.com/felipemarkson/dssdata
- Category: Interface
- License: MIT
- Package Managers: pypi:dssdata

**Additional context:**

DSSData is a python micro-framework for simulation and data analysis of electrical distribution systems modeled on OpenDSS.

**Comment by jinningwang** [comment]
Thanks for sharing! The [PR#56](https://github.com/jinningwang/best-of-ps/pull/56) has been merged, and the project should be updated this Thursday (Mar 9).
